sudo: false
language: ruby
cache: bundler
rvm:
  - jruby-1.7.25
before_install:
  - curl -s -o kafka.tgz http://ftp.wayne.edu/apache/kafka/0.9.0.1/kafka_2.11-0.9.0.1.tgz
  - mkdir kafka && tar xzf kafka.tgz -C kafka --strip-components 1
  - kafka/bin/zookeeper-server-start.sh kafka/config/zookeeper.properties &
  - kafka/bin/kafka-server-start.sh kafka/config/server.properties &
  - sleep 3
  - kafka/bin/kafka-topics.sh --create --partitions 3 --replication-factor 1 --topic logstash_topic_plain --zookeeper localhost:2181
  - kafka/bin/kafka-topics.sh --create --partitions 3 --replication-factor 1 --topic logstash_topic_snappy --zookeeper localhost:2181
  - kafka/bin/kafka-topics.sh --create --partitions 3 --replication-factor 1 --topic logstash_topic_lz4 --zookeeper localhost:2181
  - wget https://s3.amazonaws.com/data.elasticsearch.org/apache_logs/apache_logs.txt
  - cat apache_logs.txt | kafka/bin/kafka-console-producer.sh --topic logstash_topic_plain --broker-list localhost:9092
  - cat apache_logs.txt | kafka/bin/kafka-console-producer.sh --topic logstash_topic_snappy --broker-list localhost:9092 --compression-codec snappy
  - cat apache_logs.txt | kafka/bin/kafka-console-producer.sh --topic logstash_topic_lz4 --broker-list localhost:9092 --compression-codec lz4
before_script:
  - bundle exec rake vendor
  - bundle exec rake install_jars
script: bundle exec rspec && bundle exec rspec --tag integration
